services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: friendsapp
      MYSQL_USER: app
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - database_data:/var/lib/mysql:rw
    command: --default-authentication-plugin=mysql_native_password
###< doctrine/doctrine-bundle ###

  # Interface graphique pour MySQL
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
      - PMA_USER=app
      - PMA_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    depends_on:
      database:
        condition: service_healthy

###> symfony/application ###
  php:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      # Monter tout le projet y compris vendor/
      - .:/var/www/html:rw
      # Volumes pour cache et logs
      - symfony_cache:/var/www/html/var/cache:rw
      - symfony_logs:/var/www/html/var/log:rw
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://app:password@database:3306/friendsapp
      - MESSENGER_TRANSPORT_DSN=amqp://admin:password123@rabbitmq:5672/%2f/messages
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  # Service pour les tests
  php-test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html:rw
    environment:
      - APP_ENV=test
      - DATABASE_URL=mysql://app:password@database-test:3306/friendsapp_test
    depends_on:
      database-test:
        condition: service_healthy
    profiles:
      - test

  database-test:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: friendsapp_test
      MYSQL_USER: app
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - database_test_data:/var/lib/mysql:rw
    command: --default-authentication-plugin=mysql_native_password
    profiles:
      - test
###< symfony/application ###

###> symfony/messenger with rabbitmq ###
  rabbitmq:
    image: rabbitmq:4-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password123
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
###< symfony/messenger with rabbitmq ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
  database_test_data:
  symfony_cache:
  symfony_logs:
###< doctrine/doctrine-bundle ###
###> symfony/messenger with rabbitmq ###
  rabbitmq_data:
###< symfony/messenger with rabbitmq ###
